export const insurancePolicies = [
    {
        insuranceName: "LifeSecure Plus",
        insuranceType: ["Life", "Term"],
        entryAgeMin: 18,
        entryAgeMax: 65,
        sumAssuredMin: "$100,000",
        sumAssuredMax: "$1,000,000",
        premiumMin: "50",
        premiumMax: "500",
        requiresMedicalExam: "Yes, for coverage over $500,000",
        incomeCriteria: "Minimum $30,000 annual income",
        ridersAvailable: ["Critical Illness", "Accidental Death", "Disability"],
        returnOfPremium: "No",
        csr: "95%",
        features: ["Tax Benefits", "Flexible Coverage", "Online Policy Management"],
        policyTermRange: "10-30 years",
        lifeCoverTillAge: "75",
        policyTypeCategory: ["Protection", "Income Replacement"],
        payoutOptions: ["Lump Sum", "Monthly Income"],
        payoutFrequency: ["One-time", "Monthly"],
        waitingPeriod: "30 days",
    },
    {
        insuranceName: "HealthGuard Complete",
        insuranceType: ["Health", "Medical"],
        entryAgeMin: 18,
        entryAgeMax: 60,
        sumAssuredMin: "$50,000",
        sumAssuredMax: "$500,000",
        premiumMin: "100",
        premiumMax: "800",
        requiresMedicalExam: "Yes",
        incomeCriteria: null,
        ridersAvailable: ["Dental", "Vision", "Maternity"],
        returnOfPremium: "No",
        csr: null,
        features: ["Cashless Hospitalization", "Pre & Post Hospitalization Coverage", "No Claim Bonus"],
        policyTermRange: "1-3 years",
        lifeCoverTillAge: "Renewable",
        policyTypeCategory: ["Indemnity", "Fixed Benefit"],
        payoutOptions: ["Reimbursement", "Direct Settlement"],
        payoutFrequency: ["As needed"],
        waitingPeriod: "90 days for pre-existing conditions",
    },
    {
        insuranceName: "WealthBuilder Advantage",
        insuranceType: ["Life", "Investment", "Savings"],
        entryAgeMin: 18,
        entryAgeMax: 55,
        sumAssuredMin: "$20,000",
        sumAssuredMax: "$200,000",
        premiumMin: "200",
        premiumMax: "2000",
        requiresMedicalExam: "Yes",
        incomeCriteria: null,
        ridersAvailable: ["Critical Illness", "Premium Waiver"],
        returnOfPremium: "Yes, with investment returns",
        csr: "85%",
        features: ["Investment Options", "Partial Withdrawals", "Tax Benefits"],
        policyTermRange: "15-25 years",
        lifeCoverTillAge: "70",
        policyTypeCategory: ["Endowment", "Whole Life"],
        payoutOptions: ["Lump Sum", "Annuity"],
        payoutFrequency: ["Maturity", "Surrender"],
        waitingPeriod: "None",
    },
    {
        insuranceName: "SeniorCare Protect",
        insuranceType: ["Health", "Senior Care"],
        entryAgeMin: 50,
        entryAgeMax: 75,
        sumAssuredMin: "$25,000",
        sumAssuredMax: "$150,000",
        premiumMin: "150",
        premiumMax: "600",
        requiresMedicalExam: "Yes",
        incomeCriteria: null,
        ridersAvailable: ["Home Care", "Nursing", "Critical Illness"],
        returnOfPremium: "No",
        csr: null,
        features: ["No Medical Tests up to certain limit", "Specialized Senior Care", "Domiciliary Treatment"],
        policyTermRange: "5-10 years",
        lifeCoverTillAge: "85",
        policyTypeCategory: ["Medical", "Long-term Care"],
        payoutOptions: ["Reimbursement", "Cash Allowance"],
        payoutFrequency: ["As needed", "Daily for hospitalization"],
        waitingPeriod: "180 days",
    },
]
